**Array**

- Array can be store data of specified type
- Elements of an array are located in contigous
- Each element of an array has unique index

**Why need array?**

- If we need to store large data we can't use different variable for each so array or collection of variable use

**Types of Array**

1. One dimension Array: one  row and multiple columns

a=[5,4,10,11,6,34];   a[2]=10,a[4]=6

2. Two dimensional Array: bunch of values having declared with double index

a[i[j]--> i and j between 0 to n --> i= row index, j= column index

3. Three dimensional array: array with bunch of values with triple index

a[i[j][k] --> i,j and k between 0 to n --> i= depth, j= row index, k= column index

**Array in momory**

1. One dimensional: all array will be located to each other

2. two dimensional array: store as one dimensional array

3. Three dimesional array: they have depth,row and column. Also going to like 1 dimensional array


In [ ]:
#create array= more memory efficient= support basic datatypes
# creating array time complexity=O(n)
# creating array space complexity=O(n)

# no. of element increases then time to copy those elements also increases proportinally
# memory allocation also depends on number and datatype of element

import numpy as np

my_array= np.array([1,2,3,4,5])
print(my_array)

[1 2 3 4 5]


In [ ]:
# creating array time complexity=O(1)
# creating array space complexity=O(1)



arr= np.array([],dtype=int)
arr

array([], dtype=int64)

In [ ]:
#insertion array= insert element at begining,middle and last in the array

import array
arr= array.array('i',[1,2,3,4,5])
print(arr)

arr.insert(0,6)
print(arr)

arr.insert(2,6)
print(arr)

arr.insert(7,6)
print(arr)

# Time complexity= insert= depend on number of element shifted right=  O(N)
# Space complexity= need only one place= O(1)

array('i', [1, 2, 3, 4, 5])
array('i', [6, 1, 2, 3, 4, 5])
array('i', [6, 1, 6, 2, 3, 4, 5])
array('i', [6, 1, 6, 2, 3, 4, 5, 6])


In [ ]:
#Traversal operation

myarray= np.array(['a','b','c','d','e'])
for i in myarray:
  print(i)

#Time complexity = O(n)= depend on number of element
#space complexity = O(1)

a
b
c
d
e


In [ ]:
#Accessing element of array

arr1= np.array([1,2,3,4,5])


for i in range(len(arr1)):    #O(n)
  if arr1[i] > len(arr1):     #O(1)
    print('There is not element in this index')    #O(1)
  else:                     #O(1)
    print(arr1[i])          #O(1)

#Time complexity= O(n)
#Space complexity= O(1)


1
2
3
4
5


In [ ]:
#Searching an element of array= linear search algoritghm
# In Linear search iterate through the element one by one, comparing each element with target value
# if target value is found reseult successful search else value not found


arr2= np.array([1,2,3,4,5])
target= 3

def search_arr(arr,target):
  for i in range(len(arr)):
    if arr[i] == target:
      return f'Index of search array is {i}'
  return -1

print(search_arr(arr2,target))

#Time Complexity= O(n)
#Space complexity= O(1)

Index of search array is 2


In [ ]:
# Deleting element of the array

from array import *

arr3= array('i',[1,2,3,4,5])
print(arr3)

arr3.remove(2)
print(arr3)

arr3.pop(-1)
print(arr3)

#Time complexity= O(n)= after removing element all other element change there place
#Space Complexity= O(1)


array('i', [1, 2, 3, 4, 5])
array('i', [1, 3, 4, 5])
array('i', [1, 3, 4])


**Time and Space complexity of Array:**
     
1. Creating array:

  - Time Complexity: O(1)
  - Space Complexity: O(1)

2. Creating an array with elements:

  - Time Complexity: O(n)
  - Space Complexity: O(1)

3. Inserting a value in array:

  - Time Complexity: O(n)
  - Space Complexity: O(1)

4. Traversing a given array:

  - Time Complexity: O(n)
  - Space Complexity: O(1)

5. Accessing a given cell:

  - Time Complexity: O(1)
  - Space Complexity: O(1)

6. Searching a given value:

  - Time Complexity: O(n)
  - Space Complexity: O(1)

7. Deleting a given value:

  - Time Complexity: O(n)
  - Space Complexity: O(1)


In [ ]:
##Practice of All above steps

from array import *

#Create array and traverse
arr= array('i',[1,2,3,4,5])
for i in arr:
  print(f'Traverse the array:{arr}')

# access individual element of array
print(f'Accessing first element:{arr[0]}')

# append any valye into array
print(f'After append:{arr.append(10)}')

# Insert the value into array

print(f'Insert element 8 at begining:{arr.insert(0,8)}')

# Extend the array using extend()
print(f'Extend the array:{arr.extend([11,12,13])}')

# add items from the list into array using fromlist() method
lst= [14,15,16]
print(f'Add items from list into array:{arr.fromlist(lst)}')

# Remove array using remove method
print(f'Remove frommthe array using remove():{arr.remove(12)}')

#Pop array using pop method
print(f'Pop array using pop method:{arr.pop(-1)}')

# fetch element through index using index() method
print(f'Fetch element through index using index():{arr.index(2)}')

# Reverse the array
print(f'Reverse the array:{arr.reverse()}')

# Get array buffer information
print(f'Get array buffer information:{arr.buffer_info()}')

# Check number of occuerence of element
print(f'Check number of occuerence of element:{arr.count(11)}')

#convert array tro string
arr_str= arr.tobytes()
print(f'Convert array to string:{arr_str}')

# convert array to list
lst1= arr.tolist()
print(f'Convert array to list:{lst1}')

# slice element of array
print(f'Slice element of array:{arr[2:4]}')

Traverse the array:array('i', [1, 2, 3, 4, 5])
Traverse the array:array('i', [1, 2, 3, 4, 5])
Traverse the array:array('i', [1, 2, 3, 4, 5])
Traverse the array:array('i', [1, 2, 3, 4, 5])
Traverse the array:array('i', [1, 2, 3, 4, 5])
Accessing first element:1
After append:None
Insert element 8 at begining:None
Extend the array:None
Add items from list into array:None
Remove frommthe array using remove():None
Pop array using pop method:16
Fetch element through index using index():2
Reverse the array:None
Get array buffer information:(140174886906304, 11)
Check number of occuerence of element:1
Convert array to string:b'\x0f\x00\x00\x00\x0e\x00\x00\x00\r\x00\x00\x00\x0b\x00\x00\x00\n\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00'
Convert array to list:[15, 14, 13, 11, 10, 5, 4, 3, 2, 1, 8]
Slice element of array:array('i', [13, 11])


**Two Dimensional Array**

Multiple rows and multiple columns

An array with bunch of values having been declared with double index





In [ ]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

# Time complexity: O(m*n).
# Space complexity: O(m*n)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Insertion two dimension array

# addition column= move one step right
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
col_new_arr= np.insert(arr,3,[[10,11,12]],axis=1)
print(col_new_arr)



row_new_arr= np.insert(arr,0,[[10,11,12]],axis=0)
print(row_new_arr)


row_new_arr1= np.append(arr,[[10,11,12]],axis=0)
print(row_new_arr1)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
[[10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
from copy import Error
#Access element of 2D array: arr[i][j]==> i= row index and j column index
import numpy as np

arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[:][1])
print(arr[0][2])
print(arr[2][:])
print('============================')
def accessElements(arr,rowIndex,columnIndex):
  if rowIndex >= len(arr) and columnIndex >= len(arr[0]):     #O(1)
    return 'Index out of bound'                               #O(1)
  else:                                                       #O(1)
    return arr[rowIndex][columnIndex]                         #O(1)

print(accessElements(arr,2,2))
print(accessElements(arr,1,2))


#Time complexity: O(1)
#Space Complexity: O(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
3
[7 8 9]
9
6


In [ ]:
# Traversing the array
import numpy as np

arr= np.array([[1,2,3],[4,5,6],[7,8,9]])

def traverseTDArray(arr):
  for i in range(len(arr)):
    for j in range(len(arr[0])):
      print(arr[i][j])

traverseTDArray(arr)

#Time complexity: O(m*n)
#Space complexity: O(1)
#

1
2
3
4
5
6
7
8
9


In [ ]:
#search element in 2D array
import numpy as np

arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

def searchTDArray(arr,value):
  for i in range(len(arr)):
    for j in range(len(arr[0])):
      if arr[i][j] == value:
        return "The value is located index "+str(i)+" "+str(j)
  return 'The element no found'

print(searchTDArray(arr,6))
print(searchTDArray(arr,23))

#Time complexity: O(m*n)
#Space complexity: O(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The value is located index 1 2
The element no found


In [ ]:
#Deletion of 2D array

import numpy as np

arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

arr1= np.delete(arr,0,axis=1)
print(arr1)

arr2= np.delete(arr,2,axis=0)
print(arr2)
#Time complexity: O(m*n)
#Space complexity: O(1


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[1 2 3]
 [4 5 6]]


**Time and Space complexity of 2D array**


1. Creating an empty array:
   - Time complexity:  O(1)
   - Space complexity: O(1)
2. Creating an array with elements:
   - Time complexity:  O(mn)
   - Space complexity: O(mn)
3. Inserting a column/row in array:
   - Time complexity:  O(mn)
   - Space complexity: O(mn)
4. Traversing a given array:
   - Time complexity:  O(mn)
   - Space complexity: O(1)
5. Accessing a given cell:
   - Time complexity:  O(1)
   - Space complexity: O(1)
6. Searching given value:
   - Time complexity:  O(mn)
   - Space complexity: O(1)
7. Deleting a column/row:
   - Time complexity:  O(mn)
   - Space complexity: O(1)

**When to use**

- To store mutliple variable of same data type
- Random access

**When to avoid**
- Same data type elements
- Reverse memory